### ISSUE TITLE
License file is missing

### ISSUE THREAD

**Issue by bijancn** [chukmunnlee/caddy-openapi#10]
This project is really great but as there is no LICENSE file, it can't be used anywhere legally. You can find appropriate license possibilities here https://choosealicense.com/ or simply use the license that Caddy itself is using: https://github.com/caddyserver/caddy/blob/master/LICENSE

**Comment by chukmunnlee** [comment]
Added. Thanks

**Comment by bijancn** [comment]
Amazing! Thank you @chukmunnlee !
